version: "3"

tasks:
  up:
    cmds:
      - task: export-variables
      - envsubst < cluster.yaml | eksctl create cluster -f -
      - ./scripts/bootstrap.sh
  down:
    cmds:
      - task: export-variables
      - envsubst < cluster.yaml | eksctl delete cluster -f -
  export-variables:
    internal: true
    cmds:
      - export $(cat .env | xargs)
