version: "3"

tasks:
  up:
    cmds:
      - export $(cat .env | xargs)
      - envsubst < cluster.yaml | eksctl create cluster -f -
      - ./scripts/bootstrap.sh
  down:
    cmds:
      - eksctl delete cluster -f cluster.yaml
